version: '3.9'
services:
  db:
    image: postgres:12-alpine
    volumes:
      - ./.docker/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

  messaging:
    image: nats:2-alpine
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222


  # pgweb:
  #   container_name: pgweb
  #   restart: always
  #   image: sosedoff/pgweb
  #   ports:
  #     - '8081:8081'
  #   environment:
  #     - DATABASE_URL=postgres://postgres:postgres@pg:5432/db?sslmode=disable

  # redis:
  #   image: redis:alpine
  #   environment:
  #     REDIS_PASSWORD: redis
  #   ports:
  #     - 6379:6379

  # redis-commander:
  #   image: rediscommander/redis-commander:latest
  #   environment:
  #     - REDIS_HOSTS=local:redis:6379
  #   ports:
  #     - "8082:8081"
  #   depends_on:
  #       - redis